# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d5f7965608d7e3518af66b5cc8b7492407bbe02ca799cad82cafa315070b0555370d36cea1fc8cda88a62a7bc572925135a4fa70a857c5a6c05024295cf97e3

test:
  secret_key_base: 0b1ad527536e1d7bc335b45b6d057b0db9fbc92042969501f031c0ba4cd3d0a6d35d51b960c2caa5e5df74a26a842f01e37cc02ec44ec8be142053620cc652aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
